using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CSharpEssentials.LoggerHelper.SourceGenerator;

[Generator]
public sealed class SinkRegistrationGenerator : IIncrementalGenerator {
    private const string PluginInterfaceMetadataName = "CSharpEssentials.LoggerHelper.ISinkPlugin";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var compilationSinkTypes = context.CompilationProvider
            .Select(static (compilation, _) => FindAllSinkPlugins(compilation));

        context.RegisterSourceOutput(compilationSinkTypes, static (spc, sinkTypes) => {
            if (sinkTypes.IsDefaultOrEmpty)
                return;

            var source = GenerateSource(sinkTypes);
            spc.AddSource("LoggerHelperSinkRegistrations.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static ImmutableArray<INamedTypeSymbol> FindAllSinkPlugins(Compilation compilation) {
        var pluginInterface = compilation.GetTypeByMetadataName(PluginInterfaceMetadataName);
        if (pluginInterface is null)
            return ImmutableArray<INamedTypeSymbol>.Empty;

        var results = new List<INamedTypeSymbol>();

        CollectSinkTypes(compilation.Assembly.GlobalNamespace, pluginInterface, results);

        foreach (var reference in compilation.References) {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
                continue;

            var name = assembly.Name;
            if (!name.StartsWith("CSharpEssentials.LoggerHelper.Sink.", StringComparison.Ordinal)
                && !name.Equals(compilation.Assembly.Name, StringComparison.Ordinal))
                continue;

            CollectSinkTypes(assembly.GlobalNamespace, pluginInterface, results);
        }

        return results
            .Where(t => t.DeclaredAccessibility == Accessibility.Public)
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
            .ToImmutableArray();
    }

    private static void CollectSinkTypes(
        INamespaceSymbol ns,
        INamedTypeSymbol pluginInterface,
        List<INamedTypeSymbol> results) {
        foreach (var member in ns.GetMembers()) {
            switch (member) {
                case INamespaceSymbol childNs:
                    CollectSinkTypes(childNs, pluginInterface, results);
                    break;
                case INamedTypeSymbol type when type.TypeKind == TypeKind.Class && !type.IsAbstract
                    && ImplementsInterface(type, pluginInterface):
                    results.Add(type);
                    break;
            }
        }
    }

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol interfaceType) =>
        type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceType));

    private static string GenerateSource(ImmutableArray<INamedTypeSymbol> sinkTypes) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CSharpEssentials.LoggerHelper.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class LoggerHelperSinkRegistrations {");
        sb.AppendLine("    internal static bool HasRegistrations => true;");
        sb.AppendLine();
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void RegisterAllAtStartup() => RegisterAll(SinkPluginRegistry.Instance);");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterAll(ISinkPluginRegistry registry) {");

        foreach (var type in sinkTypes) {
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        registry.Register(new {fullName}());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
