name: Publish NuGet Package

on:
  push:
    branches:
      - main # or main, or any other branch where you are releasing

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Replace with your project's target framework

      - name: Install dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Create NuGet Package
        run: dotnet pack --configuration Release -o ./nupkgs

      - name: Publish NuGet Package
        run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
