name: Publish NuGet Package

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CSharpEssentials.LoggerHelper/CSharpEssentials.LoggerHelper.csproj

      - name: Build project
        run: dotnet build ./CSharpEssentials.LoggerHelper/CSharpEssentials.LoggerHelper.csproj --configuration Release --no-restore

      - name: Create NuGet package
        run: dotnet pack ./CSharpEssentials.LoggerHelper/CSharpEssentials.LoggerHelper.csproj --configuration Release --no-build -o ./nupkgs

      - name: Publish NuGet package
        run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
